package js.glob;

typedef GlobOptions = {
    ?cwd : String,
    ?root : String,
    ?dot : Bool,
    ?nomount : Bool,
    ?mark : Bool,
    ?nosort : Bool,
    ?stat : Bool,
    ?silent : Bool,
    ?strict : Bool,
    ?cache : Dynamic,
    ?statCache : Dynamic,
    ?symlinks : Dynamic,
    ?sync : Bool,
    ?nounique : Bool,
    ?nonull : Bool,
    ?debug : Bool,
    ?nobrace : Bool,
    ?noglobstar : Bool,
    ?noext : Bool,
    ?nocase : Bool,
    ?matchBase : Bool,
    ?nodir : Bool,
    ?ignore : Bool,
    ?follow : Bool,
    ?realpath : Bool,
}
